### ISSUE TITLE
[convoy-nfs] requires nolock mount option

### ISSUE THREAD

**Issue by kkvilekval** [rancher/rancher-catalog#149] opened 2016-05-17 18:17 UTC
Mounting nfs fails unless nolock is included in the mount options.  It appears that while rpcbind is started by the launch script, the rpc.statd is not.   File locking over nfs is thus unavailable.

https://github.com/rancher/convoy-agent/blob/master/packaging/convoy-agent/launch#L171

```
 5/11/2016 9:46:04 PMWaiting for metadata
    5/11/2016 9:46:04 PMtime="2016-05-12T04:46:04Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/21656/ns/mnt -F -- /var/lib/docker/aufs/mnt/9362b696c64335f026344abfdbf1ba74329ff7e039ceb8828de7041c31f6aa8f/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/convoy-nfs-47f99cab-b92d-45c2-88cb-e086cad2775a -- /launch volume-agent-nfs-internal 21656]"
    5/11/2016 9:46:04 PMRegistering convoy socket at /var/run/convoy-convoy-nfs.sock
    5/11/2016 9:46:04 PMMounting at: /var/lib/rancher/convoy/convoy-nfs-47f99cab-b92d-45c2-88cb-e086cad2775a/mnt
    5/11/2016 9:46:04 PMMounting nfs. Command: mount -t nfs -o rsize=32768,wsize=32768,noatime,intr XX.XX.XX.XX:/export/rdata/nsfdata /var/lib/rancher/convoy/convoy-nfs-47f99cab-b92d-45c2-88cb-e086cad2775a/mnt
    5/11/2016 9:46:04 PMmount.nfs: rpc.statd is not running but is required for remote locking.
    5/11/2016 9:46:04 PMmount.nfs: Either use '-o nolock' to keep locks local, or start statd.
    5/11/2016 9:46:04 PMmount.nfs: an incorrect mount option was specified
```

**Comment by janeczku** [comment] 2016-06-09 02:17
Pre-Duplicate of https://github.com/rancher/rancher/issues/4953

**Closed** 2016-10-27 02:50 UTC
